// <auto-generated />
using System;
using Fitness.CalculationEngine.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness.CalculationEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CalculationEngineDbContext))]
    [Migration("20260704105612_SeedPlansData")]
    partial class SeedPlansData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.CalculatedMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Bmr")
                        .HasColumnType("float");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("Tdee")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CalculatedMetrics");
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<double>("MaxCalorie")
                        .HasColumnType("float");

                    b.Property<double>("MinCalorie")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutsPerWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FitnessPlanConfigs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "",
                            Description = "A gentle introduction to weight loss with manageable workouts and gradual calorie reduction.",
                            EstimatedDuration = "45 minutes",
                            Goal = 1,
                            MaxCalorie = 1800.0,
                            MinCalorie = 1500.0,
                            Name = "Beginner Weight Loss",
                            ProgramType = "Cardio & Light Strength",
                            Status = 1,
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            Id = new Guid("4e8acb80-daca-4c12-9172-ba4e575bec39"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9175),
                            CreatedBy = "",
                            Description = "A gentle introduction to weight loss with manageable workouts and gradual calorie reduction.",
                            EstimatedDuration = "45 minutes",
                            Goal = 1,
                            MaxCalorie = 1800.0,
                            MinCalorie = 1500.0,
                            Name = "Beginner Weight Loss",
                            ProgramType = "Cardio & Light Strength",
                            Status = 1,
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            Id = new Guid("95a68010-8e00-4746-8666-4625c900830f"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9270),
                            CreatedBy = "",
                            Description = "Accelerated weight loss plan with increased intensity and stricter calorie management.",
                            EstimatedDuration = "60 minutes",
                            Goal = 1,
                            MaxCalorie = 1700.0,
                            MinCalorie = 1400.0,
                            Name = "Intermediate Weight Loss",
                            ProgramType = "HIIT & Strength Training",
                            Status = 2,
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            Id = new Guid("98332ee4-8420-4257-825e-503da0488608"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9274),
                            CreatedBy = "",
                            Description = "Intensive weight loss program with high-intensity workouts and aggressive calorie deficit.",
                            EstimatedDuration = "75 minutes",
                            Goal = 1,
                            MaxCalorie = 1600.0,
                            MinCalorie = 1300.0,
                            Name = "Advanced Weight Loss",
                            ProgramType = "Advanced HIIT & Compound Exercises",
                            Status = 3,
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            Id = new Guid("73a8486b-2029-43b7-92ab-596d6b1ca588"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9277),
                            CreatedBy = "",
                            Description = "Foundation building program focused on proper form and progressive overload.",
                            EstimatedDuration = "50 minutes",
                            Goal = 4,
                            MaxCalorie = 2800.0,
                            MinCalorie = 2500.0,
                            Name = "Beginner Muscle Gain",
                            ProgramType = "Full Body Strength",
                            Status = 1,
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            Id = new Guid("2c19efe0-38fe-463e-a514-a6f3bb1b7302"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9290),
                            CreatedBy = "",
                            Description = "Structured strength program with split routines and increased volume.",
                            EstimatedDuration = "65 minutes",
                            Goal = 4,
                            MaxCalorie = 3000.0,
                            MinCalorie = 2700.0,
                            Name = "Intermediate Muscle Gain",
                            ProgramType = "Upper/Lower Split",
                            Status = 2,
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            Id = new Guid("2322d375-7887-4e6d-ab66-716954bdebbb"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9294),
                            CreatedBy = "",
                            Description = "Intensive muscle building program with advanced techniques and optimal nutrition timing.",
                            EstimatedDuration = "80 minutes",
                            Goal = 4,
                            MaxCalorie = 3200.0,
                            MinCalorie = 2900.0,
                            Name = "Advanced Muscle Gain",
                            ProgramType = "Push/Pull/Legs Split",
                            Status = 3,
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            Id = new Guid("3ecc659f-25ef-4b33-80df-4fd01f061e58"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9297),
                            CreatedBy = "",
                            Description = "Build cardiovascular endurance with steady-state cardio and basic conditioning.",
                            EstimatedDuration = "40 minutes",
                            Goal = 3,
                            MaxCalorie = 2200.0,
                            MinCalorie = 2000.0,
                            Name = "Beginner Endurance",
                            ProgramType = "Steady State Cardio",
                            Status = 1,
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            Id = new Guid("fa49f170-2092-4833-a7b8-fe3175ef0a92"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9300),
                            CreatedBy = "",
                            Description = "Improve endurance with varied intensity training and longer sessions.",
                            EstimatedDuration = "55 minutes",
                            Goal = 3,
                            MaxCalorie = 2300.0,
                            MinCalorie = 2100.0,
                            Name = "Intermediate Endurance",
                            ProgramType = "Interval Training",
                            Status = 2,
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            Id = new Guid("053f6252-a964-411f-a053-64588a629801"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9304),
                            CreatedBy = "",
                            Description = "Maximum endurance training with long-distance sessions and high-volume workouts.",
                            EstimatedDuration = "90 minutes",
                            Goal = 3,
                            MaxCalorie = 2500.0,
                            MinCalorie = 2200.0,
                            Name = "Advanced Endurance",
                            ProgramType = "High Volume Cardio",
                            Status = 3,
                            WorkoutsPerWeek = 5
                        },
                        new
                        {
                            Id = new Guid("3da095c8-f789-4029-af61-0fac5bbc0215"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9307),
                            CreatedBy = "",
                            Description = "Develop fundamental strength with basic compound movements and proper technique.",
                            EstimatedDuration = "50 minutes",
                            Goal = 2,
                            MaxCalorie = 2400.0,
                            MinCalorie = 2200.0,
                            Name = "Beginner Strength",
                            ProgramType = "Compound Lifts",
                            Status = 1,
                            WorkoutsPerWeek = 3
                        },
                        new
                        {
                            Id = new Guid("25092462-c3de-4177-81fe-0580e173c4c6"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9311),
                            CreatedBy = "",
                            Description = "Increase strength with progressive overload and accessory exercises.",
                            EstimatedDuration = "70 minutes",
                            Goal = 2,
                            MaxCalorie = 2600.0,
                            MinCalorie = 2400.0,
                            Name = "Intermediate Strength",
                            ProgramType = "Powerlifting Focus",
                            Status = 2,
                            WorkoutsPerWeek = 4
                        },
                        new
                        {
                            Id = new Guid("8cc6da4d-a98d-4dca-b905-cf06f6a8c60c"),
                            CreatedAt = new DateTime(2026, 7, 4, 10, 56, 9, 323, DateTimeKind.Utc).AddTicks(9325),
                            CreatedBy = "",
                            Description = "Maximal strength development with periodization and peak performance training.",
                            EstimatedDuration = "90 minutes",
                            Goal = 2,
                            MaxCalorie = 2800.0,
                            MinCalorie = 2600.0,
                            Name = "Advanced Strength",
                            ProgramType = "Strength & Power",
                            Status = 3,
                            WorkoutsPerWeek = 4
                        });
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAssignedPlans");
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.UserFitnessStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Goal")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFitnessStats");
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.UserPlanHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonForChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlanHistories");
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.UserAssignedPlan", b =>
                {
                    b.HasOne("Fitness.CalculationEngine.Domain.Entities.FitnessPlanConfig", "FitnessPlanConfig")
                        .WithMany("UserAssignedPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FitnessPlanConfig");
                });

            modelBuilder.Entity("Fitness.CalculationEngine.Domain.Entities.FitnessPlanConfig", b =>
                {
                    b.Navigation("UserAssignedPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
