// <auto-generated />
using System;
using Fitness.Nutrition.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness.Nutrition.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NutritionDbContext))]
    [Migration("20260711145407_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Brown Rice"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Salmon"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Quinoa"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Spinach"
                        },
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789aaa"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Eggs"
                        },
                        new
                        {
                            Id = new Guid("23456789-2345-2345-2345-23456789bbbb"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Oats"
                        },
                        new
                        {
                            Id = new Guid("3456789a-3456-3456-3456-3456789acccc"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Greek Yogurt"
                        },
                        new
                        {
                            Id = new Guid("456789ab-4567-4567-4567-456789abdddd"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Name = "Avocado"
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllergensJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AllergensJson = "[\"None\"]",
                            Calories = 350.0,
                            Carbs = 25.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Easy",
                            Fats = 12.0,
                            ImageUrl = "https://example.com/images/chicken-rice.jpg",
                            IngredientsJson = "[\"2 Chicken Breasts\", \"1 cup Brown Rice\", \"1 cup Broccoli\"]",
                            InstructionsJson = "[\"Season chicken with salt and pepper\", \"Grill chicken for 6-8 minutes per side\", \"Cook rice according to package directions\", \"Steam broccoli until tender\"]",
                            Name = "Grilled Chicken with Brown Rice",
                            PrepTimeInMinutes = 25,
                            Protein = 32.0,
                            TagsJson = "[\"High Protein\", \"Low Fat\", \"Healthy\"]",
                            Type = "Lunch",
                            VariationsJson = "[\"Use quinoa instead of rice\", \"Add bell peppers\"]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AllergensJson = "[\"Fish\"]",
                            Calories = 420.0,
                            Carbs = 45.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Medium",
                            Fats = 14.0,
                            ImageUrl = "https://example.com/images/salmon-quinoa.jpg",
                            IngredientsJson = "[\"2 Salmon Fillets\", \"1 cup Quinoa\", \"2 cups Spinach\", \"1 Avocado\"]",
                            InstructionsJson = "[\"Season salmon with lemon and herbs\", \"Bake at 375°F for 15-20 minutes\", \"Cook quinoa as directed\", \"Serve over spinach with sliced avocado\"]",
                            Name = "Salmon Quinoa Bowl",
                            PrepTimeInMinutes = 30,
                            Protein = 28.0,
                            TagsJson = "[\"Omega-3\", \"Heart Healthy\", \"Gluten-Free\"]",
                            Type = "Dinner",
                            VariationsJson = "[\"Add roasted vegetables\", \"Use wild rice instead of quinoa\"]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AllergensJson = "[\"Eggs\", \"Dairy\"]",
                            Calories = 480.0,
                            Carbs = 30.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Easy",
                            Fats = 22.0,
                            ImageUrl = "https://example.com/images/egg-oat-bowl.jpg",
                            IngredientsJson = "[\"3 Eggs\", \"1/2 cup Oats\", \"1/2 cup Greek Yogurt\"]",
                            InstructionsJson = "[\"Cook oats with water or milk\", \"Scramble eggs separately\", \"Combine in bowl\", \"Top with Greek yogurt\"]",
                            Name = "Egg and Oat Breakfast Bowl",
                            PrepTimeInMinutes = 15,
                            Protein = 35.0,
                            TagsJson = "[\"High Protein\", \"Breakfast\", \"Quick\"]",
                            Type = "Breakfast",
                            VariationsJson = "[\"Add berries\", \"Use almond milk\"]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AllergensJson = "[\"Soy\"]",
                            Calories = 300.0,
                            Carbs = 20.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Medium",
                            Fats = 10.0,
                            ImageUrl = "https://example.com/images/stir-fry.jpg",
                            IngredientsJson = "[\"2 Chicken Breasts\", \"2 cups Mixed Vegetables\", \"2 tbsp Soy Sauce\"]",
                            InstructionsJson = "[\"Cut chicken into strips\", \"Stir-fry chicken in hot pan\", \"Add vegetables and cook until tender\", \"Add soy sauce and season\"]",
                            Name = "Chicken and Vegetable Stir-fry",
                            PrepTimeInMinutes = 20,
                            Protein = 25.0,
                            TagsJson = "[\"Quick\", \"Healthy\", \"Low Calorie\"]",
                            Type = "Dinner",
                            VariationsJson = "[\"Use tofu instead of chicken\", \"Add ginger and garlic\"]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            AllergensJson = "[\"Dairy\"]",
                            Calories = 280.0,
                            Carbs = 35.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Easy",
                            Fats = 8.0,
                            ImageUrl = "https://example.com/images/parfait.jpg",
                            IngredientsJson = "[\"1 cup Greek Yogurt\", \"1/2 cup Berries\", \"1/4 cup Granola\"]",
                            InstructionsJson = "[\"Layer yogurt in a glass\", \"Add berries\", \"Top with granola\"]",
                            Name = "Greek Yogurt Parfait",
                            PrepTimeInMinutes = 5,
                            Protein = 18.0,
                            TagsJson = "[\"Quick\", \"Healthy\", \"Snack\"]",
                            Type = "Snack",
                            VariationsJson = "[\"Use different fruits\", \"Add honey\"]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            AllergensJson = "[\"Fish\"]",
                            Calories = 550.0,
                            Carbs = 15.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Difficulty = "Easy",
                            Fats = 35.0,
                            ImageUrl = "https://example.com/images/salmon-salad.jpg",
                            IngredientsJson = "[\"2 Salmon Fillets\", \"1 Avocado\", \"2 cups Spinach\"]",
                            InstructionsJson = "[\"Bake or pan-sear salmon\", \"Slice avocado\", \"Arrange over spinach\", \"Add light dressing\"]",
                            Name = "Avocado Salmon Salad",
                            PrepTimeInMinutes = 15,
                            Protein = 40.0,
                            TagsJson = "[\"Keto\", \"High Protein\", \"Healthy Fats\"]",
                            Type = "Lunch",
                            VariationsJson = "[\"Add nuts\", \"Use mixed greens\"]"
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("MealId");

                    b.ToTable("MealIngredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Amount = "2 breasts",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            MealId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Amount = "1 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            MealId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            Amount = "1 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            MealId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a"),
                            Amount = "2 fillets",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            MealId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("e5f6a7b8-c9d0-4e1f-2a3b-4c5d6e7f8a9b"),
                            Amount = "1 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            MealId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-d0e1-4f2a-3b4c-5d6e7f8a9b0c"),
                            Amount = "2 cups",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            MealId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-e1f2-4a3b-4c5d-6e7f8a9b0c1d"),
                            Amount = "1",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("456789ab-4567-4567-4567-456789abdddd"),
                            MealId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b8c9d0e1-f2a3-4b4c-5d6e-7f8a9b0c1d2e"),
                            Amount = "3",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("12345678-1234-1234-1234-123456789aaa"),
                            MealId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("c9d0e1f2-a3b4-4c5d-6e7f-8a9b0c1d2e3f"),
                            Amount = "1/2 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("23456789-2345-2345-2345-23456789bbbb"),
                            MealId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("d0e1f2a3-b4c5-4d6e-7f8a-9b0c1d2e3f4a"),
                            Amount = "1/2 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("3456789a-3456-3456-3456-3456789acccc"),
                            MealId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            Amount = "2 breasts",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            MealId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c"),
                            Amount = "2 cups",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            MealId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("a3b4c5d6-e7f8-4a9b-0c1d-2e3f4a5b6c7d"),
                            Amount = "1 cup",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("3456789a-3456-3456-3456-3456789acccc"),
                            MealId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("b4c5d6e7-f8a9-4b0c-1d2e-3f4a5b6c7d8e"),
                            Amount = "2 fillets",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            MealId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("c5d6e7f8-a9b0-4c1d-2e3f-4a5b6c7d8e9f"),
                            Amount = "1",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("456789ab-4567-4567-4567-456789abdddd"),
                            MealId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("d6e7f8a9-b0c1-4d2e-3f4a-5b6c7d8e9f0a"),
                            Amount = "2 cups",
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            IngredientId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            MealId = new Guid("66666666-6666-6666-6666-666666666666")
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TargetCalorieRangeMax")
                        .HasColumnType("float");

                    b.Property<double>("TargetCalorieRangeMin")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12345678-1234-1234-1234-123456789abc"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Description = "A balanced meal plan designed for steady weight loss with high protein and moderate carbs.",
                            Name = "Weekly Weight Loss Plan",
                            TargetCalorieRangeMax = 1800.0,
                            TargetCalorieRangeMin = 1500.0
                        },
                        new
                        {
                            Id = new Guid("23456789-2345-2345-2345-23456789abcd"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Description = "High protein meal plan for muscle growth and recovery.",
                            Name = "Muscle Building Plan",
                            TargetCalorieRangeMax = 2800.0,
                            TargetCalorieRangeMin = 2500.0
                        },
                        new
                        {
                            Id = new Guid("3456789a-3456-3456-3456-3456789abcde"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Description = "Low carb, high fat meal plan for ketosis.",
                            Name = "Keto Diet Plan",
                            TargetCalorieRangeMax = 2200.0,
                            TargetCalorieRangeMin = 2000.0
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MealPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("MealPlanId");

                    b.ToTable("MealPlanItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7f8a9b0-c1d2-4e3f-4a5b-6c7d8e9f0a1b"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("f8a9b0c1-d2e3-4f4a-5b6c-7d8e9f0a1b2c"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("a9b0c1d2-e3f4-4a5b-6c7d-8e9f0a1b2c3d"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("44444444-4444-4444-4444-444444444444"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("b0c1d2e3-f4a5-4b6c-7d8e-9f0a1b2c3d4e"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Tuesday",
                            MealId = new Guid("55555555-5555-5555-5555-555555555555"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Tuesday",
                            MealId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("d2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Tuesday",
                            MealId = new Guid("66666666-6666-6666-6666-666666666666"),
                            MealPlanId = new Guid("12345678-1234-1234-1234-123456789abc"),
                            MealTime = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("e3f4a5b6-c7d8-4e9f-0a1b-2c3d4e5f6a7b"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MealPlanId = new Guid("23456789-2345-2345-2345-23456789abcd"),
                            MealTime = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("f4a5b6c7-d8e9-4f0a-1b2c-3d4e5f6a7b8c"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("11111111-1111-1111-1111-111111111111"),
                            MealPlanId = new Guid("23456789-2345-2345-2345-23456789abcd"),
                            MealTime = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("a5b6c7d8-e9f0-4a1b-2c3d-4e5f6a7b8c9d"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MealPlanId = new Guid("23456789-2345-2345-2345-23456789abcd"),
                            MealTime = "Dinner"
                        },
                        new
                        {
                            Id = new Guid("b6c7d8e9-f0a1-4b2c-3d4e-5f6a7b8c9d0e"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Tuesday",
                            MealId = new Guid("66666666-6666-6666-6666-666666666666"),
                            MealPlanId = new Guid("23456789-2345-2345-2345-23456789abcd"),
                            MealTime = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("c7d8e9f0-a1b2-4c3d-4e5f-6a7b8c9d0e1f"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("66666666-6666-6666-6666-666666666666"),
                            MealPlanId = new Guid("3456789a-3456-3456-3456-3456789abcde"),
                            MealTime = "Breakfast"
                        },
                        new
                        {
                            Id = new Guid("d8e9f0a1-b2c3-4d4e-5f6a-7b8c9d0e1f2a"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("66666666-6666-6666-6666-666666666666"),
                            MealPlanId = new Guid("3456789a-3456-3456-3456-3456789abcde"),
                            MealTime = "Lunch"
                        },
                        new
                        {
                            Id = new Guid("e9f0a1b2-c3d4-4e5f-6a7b-8c9d0e1f2a3b"),
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            DayOfWeek = "Monday",
                            MealId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MealPlanId = new Guid("3456789a-3456-3456-3456-3456789abcde"),
                            MealTime = "Dinner"
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.NutritionFacts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<double>("Carbs")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<double>("Fiber")
                        .HasColumnType("float");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MealId")
                        .IsUnique();

                    b.ToTable("NutritionFacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-1111111111a1"),
                            Calories = 350,
                            Carbs = 25.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 12.0,
                            Fiber = 4.0,
                            MealId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Protein = 32.0
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-2222222222b2"),
                            Calories = 420,
                            Carbs = 45.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 14.0,
                            Fiber = 6.0,
                            MealId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Protein = 28.0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-3333333333c3"),
                            Calories = 480,
                            Carbs = 30.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 22.0,
                            Fiber = 3.0,
                            MealId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Protein = 35.0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-4444444444d4"),
                            Calories = 300,
                            Carbs = 20.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 10.0,
                            Fiber = 5.0,
                            MealId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Protein = 25.0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-5555555555e5"),
                            Calories = 280,
                            Carbs = 35.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 8.0,
                            Fiber = 7.0,
                            MealId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Protein = 18.0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-6666666666f6"),
                            Calories = 550,
                            Carbs = 15.0,
                            CreatedAt = new DateTime(2026, 7, 11, 14, 54, 7, 368, DateTimeKind.Utc).AddTicks(9122),
                            CreatedBy = "System",
                            Fats = 35.0,
                            Fiber = 8.0,
                            MealId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Protein = 40.0
                        });
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealIngredient", b =>
                {
                    b.HasOne("Fitness.Nutrition.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness.Nutrition.Domain.Entities.Meal", "Meal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealPlanItem", b =>
                {
                    b.HasOne("Fitness.Nutrition.Domain.Entities.Meal", "Meal")
                        .WithMany("MealPlanItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness.Nutrition.Domain.Entities.MealPlan", "MealPlan")
                        .WithMany("MealPlanItems")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("MealPlan");
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.NutritionFacts", b =>
                {
                    b.HasOne("Fitness.Nutrition.Domain.Entities.Meal", "Meal")
                        .WithOne("NutritionFacts")
                        .HasForeignKey("Fitness.Nutrition.Domain.Entities.NutritionFacts", "MealId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.Meal", b =>
                {
                    b.Navigation("MealIngredients");

                    b.Navigation("MealPlanItems");

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness.Nutrition.Domain.Entities.MealPlan", b =>
                {
                    b.Navigation("MealPlanItems");
                });
#pragma warning restore 612, 618
        }
    }
}
